import {rest,config} from '../../supabase';
import { authorized,catalog,photos,json,HttpError,sameOrigin,saveProperty } from '../../store';
export const dynamic='force-dynamic';
async function handler(req:Request){try{const path=new URL(req.url).pathname.split('/').slice(2);
if(path[0]==='catalog'&&req.method==='GET')return json(await catalog());
if(path[0]==='gallery'&&req.method==='GET'){const id=new URL(req.url).searchParams.get('id');const p=(await catalog()).find(p=>p.id===id);if(!p)throw new HttpError(404,'Imóvel não encontrado.');return json({images:photos(p)});}
if(path[0]==='media'&&req.method==='GET'){const key=path[1];if(!/^[a-f0-9-]+\.(jpg|png|webp)$/.test(key))throw new HttpError(404,'Foto não encontrada.');const file=await fetch(config().url+'/storage/v1/object/public/property-images/'+key,{signal:AbortSignal.timeout(15000)});if(!file.ok)throw new HttpError(404,'Foto não encontrada.');return new Response(file.body,{headers:{'Content-Type':file.headers.get('content-type')||'application/octet-stream','Cache-Control':'public,max-age=31536000,immutable','X-Content-Type-Options':'nosniff'}});}
if(req.method!=='GET')sameOrigin(req);
if(path[0]==='lead'&&req.method==='POST'){if(Number(req.headers.get('content-length')||0)>12000)throw new HttpError(413,'Mensagem muito longa.');const v=await req.json();if(v.website)return json({ok:true});const name=String(v.name||'').trim(),phone=String(v.phone||'').trim(),email=String(v.email||'').trim(),goal=String(v.goal||'').trim(),wish=String(v.wish||'').trim();if(name.length<2||name.length>100||phone.length>30||goal.length>160||!goal||wish.length>3000)throw new HttpError(400,'Confira os campos do contato.');if(!/^[\d\s()+-]{10,30}$/.test(phone)||phone.replace(/\D/g,'').length<10||phone.replace(/\D/g,'').length>15)throw new HttpError(400,'Confira o telefone.');if(email&&(email.length>254||!/^([^\s@]+)@([^\s@]+)\.([^\s@]+)$/.test(email)))throw new HttpError(400,'Confira o e-mail.');const id=String(v.id||'');if(!/^[a-f0-9-]{36}$/.test(id))throw new HttpError(400,'Pedido inválido.');await rest('leads?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates'},body:JSON.stringify({id,name,phone,email,goal,wish,status:'Novo',created_at:new Date().toISOString()})});return json({ok:true});}
if(path[0]==='event'&&req.method==='POST'){const v=await req.json();const route=String(v.route||'');const kind=String(v.kind||'');const valid=['inicio','imoveis','arianne','contato'].includes(route)||(route.startsWith('imovel/')&&(await catalog()).some(p=>'imovel/'+p.id===route));if(!valid||!['view','whatsapp'].includes(kind))throw new HttpError(400,'Evento inválido.');const day=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(new Date());await rest('rpc/increment_site_metric',{method:'POST',body:JSON.stringify({p_day:day,p_route:route,p_kind:kind})});return json({ok:true});}
await authorized();
if(path[0]==='admin'&&path[1]==='properties'&&req.method==='GET')return json((await catalog(true)).map(p=>({...p,revision:p.revision||0,images:photos(p)})));
if(path[0]==='admin'&&path[1]==='property'&&req.method==='PUT'){const v=await req.json();return json(await saveProperty(path[2],v.property,Number(v.revision)));}
if(path[0]==='admin'&&path[1]==='leads'&&req.method==='GET')return json(await rest('leads?select=*&order=created_at.desc&limit=1000'));
if(path[0]==='admin'&&path[1]==='lead'&&req.method==='PATCH'){const v=await req.json();if(!['Novo','Em atendimento','Visita agendada','Concluído'].includes(v.status))throw new HttpError(400,'Status inválido.');if(!/^[a-f0-9-]{36}$/.test(path[2]))throw new HttpError(400,'Contato inválido.');await rest('leads?id=eq.'+encodeURIComponent(path[2]),{method:'PATCH',body:JSON.stringify({status:v.status})});return json({ok:true});}
if(path[0]==='admin'&&path[1]==='stats'&&req.method==='GET'){const since=new Date(Date.now()-29*86400000).toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'});return json(await rest('daily_metrics?select=day,route,kind,count&day=gte.'+since+'&order=day'));}
if(path[0]==='admin'&&path[1]==='upload'&&req.method==='POST'){const form=await req.formData();const file=form.get('file');if(!(file instanceof File)||file.size>12*1024*1024||file.size<12)throw new HttpError(400,'Envie uma imagem de até 12 MB.');const data=await file.arrayBuffer(),bytes=new Uint8Array(data);let ext='',type='';if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255){ext='jpg';type='image/jpeg';}else if(bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71){ext='png';type='image/png';}else if(new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP'){ext='webp';type='image/webp';}else throw new HttpError(400,'Use JPG, PNG ou WebP.');const key=crypto.randomUUID()+'.'+ext;const c=config();const uploaded=await fetch(c.url+'/storage/v1/object/property-images/'+key,{method:'POST',headers:{apikey:c.secret,'Content-Type':type,'x-upsert':'false'},body:data,signal:AbortSignal.timeout(30000)});if(!uploaded.ok)throw new HttpError(503,'Não foi possível enviar a foto. Tente novamente.');return json({url:'/api/media/'+key});}
throw new HttpError(404,'Não encontrado.');
}catch(e){if(e instanceof HttpError)return json({error:e.message},e.status);console.error('site-api',e);return json({error:'Não foi possível concluir agora. Seus dados não foram descartados; tente novamente.'},503);}}
export const GET=handler;export const POST=handler;export const PUT=handler;export const PATCH=handler;
