import { env } from 'cloudflare:workers';
import { authorized,catalog,photos,database,json,HttpError,sameOrigin,saveProperty } from '../../store';
export const dynamic='force-dynamic';
async function handler(req:Request){try{const path=new URL(req.url).pathname.split('/').slice(2);const db=database();
if(path[0]==='catalog'&&req.method==='GET')return json(await catalog());
if(path[0]==='gallery'&&req.method==='GET'){const id=new URL(req.url).searchParams.get('id');const p=(await catalog()).find(p=>p.id===id);if(!p)throw new HttpError(404,'Imóvel não encontrado.');return json({images:photos(p)});}
if(path[0]==='media'&&req.method==='GET'){const key=path[1];if(!/^[a-f0-9-]+\.(jpg|png|webp)$/.test(key))throw new HttpError(404,'Foto não encontrada.');const file=await (env as any).BUCKET.get(key);if(!file)throw new HttpError(404,'Foto não encontrada.');return new Response(file.body,{headers:{'Content-Type':file.httpMetadata?.contentType||'application/octet-stream','Cache-Control':'public,max-age=31536000,immutable','X-Content-Type-Options':'nosniff'}});}
if(req.method!=='GET')sameOrigin(req);
if(path[0]==='lead'&&req.method==='POST'){if(Number(req.headers.get('content-length')||0)>12000)throw new HttpError(413,'Mensagem muito longa.');const v=await req.json();if(v.website)return json({ok:true});const name=String(v.name||'').trim(),phone=String(v.phone||'').trim(),email=String(v.email||'').trim(),goal=String(v.goal||'').trim(),wish=String(v.wish||'').trim();if(name.length<2||name.length>100||phone.length>30||goal.length>160||!goal||wish.length>3000)throw new HttpError(400,'Confira os campos do contato.');if(!/^[\d\s()+-]{10,30}$/.test(phone)||phone.replace(/\D/g,'').length<10||phone.replace(/\D/g,'').length>15)throw new HttpError(400,'Confira o telefone.');if(email&&(email.length>254||!/^([^\s@]+)@([^\s@]+)\.([^\s@]+)$/.test(email)))throw new HttpError(400,'Confira o e-mail.');const id=String(v.id||'');if(!/^[a-f0-9-]{36}$/.test(id))throw new HttpError(400,'Pedido inválido.');await db.prepare('INSERT OR IGNORE INTO leads(id,name,phone,email,goal,wish,status,created_at) VALUES (?,?,?,?,?,?,?,?)').bind(id,name,phone,email,goal,wish,'Novo',new Date().toISOString()).run();return json({ok:true});}
if(path[0]==='event'&&req.method==='POST'){const v=await req.json();const route=String(v.route||'');const kind=String(v.kind||'');const valid=['inicio','imoveis','arianne','contato'].includes(route)||(route.startsWith('imovel/')&&(await catalog()).some(p=>'imovel/'+p.id===route));if(!valid||!['view','whatsapp'].includes(kind))throw new HttpError(400,'Evento inválido.');const day=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(new Date());await db.prepare('INSERT INTO daily_metrics(day,route,kind,count) VALUES (?,?,?,1) ON CONFLICT(day,route,kind) DO UPDATE SET count=count+1').bind(day,route,kind).run();return json({ok:true});}
await authorized();
if(path[0]==='admin'&&path[1]==='properties'&&req.method==='GET')return json((await catalog(true)).map(p=>({...p,revision:p.revision||0,images:photos(p)})));
if(path[0]==='admin'&&path[1]==='property'&&req.method==='PUT'){const v=await req.json();return json(await saveProperty(path[2],v.property,Number(v.revision)));}
if(path[0]==='admin'&&path[1]==='leads'&&req.method==='GET')return json((await db.prepare('SELECT * FROM leads ORDER BY created_at DESC LIMIT 1000').all()).results);
if(path[0]==='admin'&&path[1]==='lead'&&req.method==='PATCH'){const v=await req.json();if(!['Novo','Em atendimento','Visita agendada','Concluído'].includes(v.status))throw new HttpError(400,'Status inválido.');await db.prepare('UPDATE leads SET status=? WHERE id=?').bind(v.status,path[2]).run();return json({ok:true});}
if(path[0]==='admin'&&path[1]==='stats'&&req.method==='GET'){const since=new Date(Date.now()-29*86400000).toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'});return json((await db.prepare('SELECT day,route,kind,count FROM daily_metrics WHERE day>=? ORDER BY day').bind(since).all()).results);}
if(path[0]==='admin'&&path[1]==='upload'&&req.method==='POST'){const form=await req.formData();const file=form.get('file');if(!(file instanceof File)||file.size>12*1024*1024||file.size<12)throw new HttpError(400,'Envie uma imagem de até 12 MB.');const data=await file.arrayBuffer(),bytes=new Uint8Array(data);let ext='',type='';if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255){ext='jpg';type='image/jpeg';}else if(bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71){ext='png';type='image/png';}else if(new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP'){ext='webp';type='image/webp';}else throw new HttpError(400,'Use JPG, PNG ou WebP.');const key=crypto.randomUUID()+'.'+ext;await (env as any).BUCKET.put(key,data,{httpMetadata:{contentType:type}});return json({url:'/api/media/'+key});}
throw new HttpError(404,'Não encontrado.');
}catch(e){if(e instanceof HttpError)return json({error:e.message},e.status);console.error('site-api',e);return json({error:'Não foi possível concluir agora. Seus dados não foram descartados; tente novamente.'},503);}}
export const GET=handler;export const POST=handler;export const PUT=handler;export const PATCH=handler;
