const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),ts=require('typescript');
process.env.SUPABASE_URL='https://test.supabase.co';process.env.SUPABASE_PUBLISHABLE_KEY='sb_publishable_test';process.env.SUPABASE_SECRET_KEY='sb_secret_test';
const jar=new Map(),cookieOptions=[],overrides=new Map(),leads=new Map(),metrics=new Map();
const cookies={get:k=>jar.has(k)?{value:jar.get(k)}:undefined,set:(k,v,o)=>{jar.set(k,v);cookieOptions.push(o)}};
global.fetch=async(input,options={})=>{const u=new URL(String(input)),p=u.pathname,body=options.body?JSON.parse(options.body):{};const token=options.headers?.Authorization;const ok=d=>Response.json(d);if(p==='/auth/v1/user')return token==='Bearer good'?ok({id:'owner',email:'test@example.test',email_confirmed_at:'yes'}):new Response(null,{status:401});if(p==='/auth/v1/token')return ok({access_token:'good',refresh_token:'refresh',expires_in:3600,user:{email_confirmed_at:'yes'}});if(p.includes('rpc/is_site_admin'))return ok(token==='Bearer good');if(p.includes('rpc/increment_site_metric')){const key=body.p_day+body.p_route+body.p_kind;metrics.set(key,(metrics.get(key)||0)+1);return new Response(null,{status:204});}if(p.endsWith('/property_overrides')){if(options.method==='POST'){if(overrides.has(body.id))return new Response('{}',{status:409});overrides.set(body.id,body);return ok([body]);}if(options.method==='PATCH'){const id=u.searchParams.get('id').slice(3),rev=+u.searchParams.get('revision').slice(3),current=overrides.get(id);if(current?.revision!==rev)return ok([]);const value={...current,...body};overrides.set(id,value);return ok([value]);}return ok([...overrides.values()]);}if(p.endsWith('/leads')){if(options.method==='POST'){if(!leads.has(body.id))leads.set(body.id,body);return new Response(null,{status:201});}return ok([...leads.values()]);}if(p.endsWith('/daily_metrics'))return ok([]);throw Error('Unexpected request '+u);};
const cache={};function load(file){file=path.resolve(file);if(cache[file])return cache[file];const result={exports:{}};cache[file]=result.exports;const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true,resolveJsonModule:true}}).outputText;function req(p){if(p==='next/headers')return{cookies:async()=>cookies};if(p.startsWith('.')){const dest=path.resolve(path.dirname(file),p);if(dest.endsWith('.json'))return JSON.parse(fs.readFileSync(dest));return load(dest+'.ts');}return require(p);}new Function('require','module','exports',code)(req,result,result.exports);cache[file]=result.exports;return result.exports;}
const api=load('app/api/[...path]/route.ts'),store=load('app/store.ts'),auth=load('app/supabase.ts'),home=load('app/route.ts'),login=load('app/api/auth/login/route.ts');
const request=(route,method='GET',body,origin='https://site.test')=>new Request('https://site.test/api/'+route,{method,headers:{Origin:origin,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
assert.doesNotThrow(()=>auth.sameOrigin(new Request('http://internal.netlify/api/auth/login',{headers:{Origin:'https://arianne-costa-imoveis.netlify.app'}})));
for(const origin of ['https://evil.test','https://arianne-costa-imoveis.netlify.app.evil.test','null'])assert.throws(()=>auth.sameOrigin(new Request('http://internal.netlify/api/auth/login',{headers:{Origin:origin,'X-Forwarded-Host':'evil.test'}})),e=>e.status===403);
assert.throws(()=>auth.sameOrigin(new Request('http://internal.netlify/api/auth/login')),e=>e.status===403);
(async()=>{assert.equal((await api.GET(request('admin/leads'))).status,401);jar.set('ac-access','bad');assert.equal((await api.GET(request('admin/leads'))).status,401);jar.set('ac-access','good');assert.equal((await api.GET(request('admin/leads'))).status,200);assert.equal((await api.POST(request('lead','POST',{},'https://evil.test'))).status,403);
const props=await store.catalog();assert.equal(props.length,460);const p=props[0];assert.ok(store.photos(p).length>2);await store.saveProperty(p.id,{...p,price:1234567},0);assert.equal((await store.catalog()).find(x=>x.id===p.id).price,1234567);await assert.rejects(()=>store.saveProperty(p.id,p,0),e=>e.status===409);await assert.rejects(()=>store.saveProperty(p.id,p,9),e=>e.status===409);await assert.rejects(()=>store.saveProperty(p.id,{...p,images:['javascript:bad']},1),e=>e.status===400);await store.saveProperty(p.id,{...p,hidden:true},1);assert.equal((await api.GET(request('gallery?id='+p.id))).status,404);
const lead={id:crypto.randomUUID(),name:'Pessoa teste',phone:'41999999999',email:'',goal:'Agendar uma visita',wish:'Teste local'};assert.equal((await api.POST(request('lead','POST',{...lead,phone:''}))).status,400);assert.equal((await api.POST(request('lead','POST',{...lead,email:'inválido'}))).status,400);assert.equal((await api.POST(request('lead','POST',lead))).status,200);assert.equal((await api.POST(request('lead','POST',lead))).status,200);assert.equal(leads.size,1);assert.equal(leads.get(lead.id).phone,lead.phone);
assert.equal((await api.POST(request('event','POST',{route:'inicio',kind:'view'}))).status,200);assert.equal((await api.POST(request('event','POST',{route:'inicio',kind:'view'}))).status,200);assert.equal([...metrics.values()][0],2);assert.equal((await api.POST(request('event','POST',{route:'invalid',kind:'view'}))).status,400);
const html=await(await home.GET()).text();assert.ok(html.includes('lead-phone'));assert.ok(html.includes('continue-whatsapp'));assert.ok(!html.includes('sb_secret_test'));const logged=await login.POST(request('auth/login','POST',{email:'test@example.test',password:'pass'}));assert.equal(logged.status,200);assert.ok(cookieOptions.every(o=>o.httpOnly&&o.sameSite==='lax'));assert.ok(jar.get('ac-refresh'));console.log('Passed: admin gate, CSRF, 460 properties, full gallery, saves/conflicts/hiding, phone/optional email, lead dedup, metrics, safe public HTML, login cookies.');})().catch(e=>{console.error(e);process.exit(1)});
