import { env } from 'cloudflare:workers';
import { getChatGPTUser } from './chatgpt-auth';
import base from './data/catalogo.json';
import galleries from './data/galerias.json';
export const ADMIN_EMAIL='ariannecostaimoveis@gmail.com';
export const database=()=>{const db=(env as any).DB;if(!db)throw new Error('Banco indisponível');return db;};
export const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
export class HttpError extends Error { constructor(public status:number,message:string){super(message);} }
export async function authorized(){const u=await getChatGPTUser();if(!u)throw new HttpError(401,'Entre com a conta autorizada.');if(![ADMIN_EMAIL,String((env as any).ADMIN_OWNER_EMAIL||'').toLowerCase()].filter(Boolean).includes(u.email.toLowerCase()))throw new HttpError(403,'Esta conta não tem acesso ao painel.');const db=database();await db.prepare('INSERT OR IGNORE INTO admin_identity(email,user_id) VALUES (?,?)').bind(u.email.toLowerCase(),u.userId).run();const record=await db.prepare('SELECT user_id FROM admin_identity WHERE email=?').bind(u.email.toLowerCase()).first();if(record?.user_id!==u.userId)throw new HttpError(403,'Conta não autorizada.');return u;}
export function sameOrigin(req:Request){if(req.headers.get('Origin')!==new URL(req.url).origin)throw new HttpError(403,'Origem não autorizada.');}
export async function catalog(includeHidden=false){const results=await database().prepare('SELECT id,data,revision FROM property_overrides').all();const overrides=new Map(results.results.map((r:any)=>[r.id,{...JSON.parse(r.data),revision:r.revision}]));const list=(base as any[]).map(p=>({...p,...overrides.get(p.id),id:p.id}));for(const [id,p] of overrides)if(!list.some(r=>r.id===id))list.push(p);return includeHidden?list:list.filter(p=>!p.hidden);}
export function photos(p:any){return p.customGallery||!(galleries as any)[p.id] ? p.images : (galleries as any)[p.id].images;}
const txt=(v:unknown,max=200)=>String(v??'').trim().slice(0,max);
export function validateProperty(value:any){if(!value||typeof value!=='object')throw new HttpError(400,'Dados inválidos.');const p:any={};for(const key of ['title','bairro','area','type','status','code','category','totalArea','bathrooms','suites','parking','delivery','condominium','iptu','areaLabel'])p[key]=txt(value[key],200);p.description=txt(value.description,5000);if(!p.title||!p.bairro||!p.type)throw new HttpError(400,'Informe título, bairro e tipo.');p.area=p.area||'Consulte';p.areaLabel=p.areaLabel||'m² no anúncio';p.category=p.category||'apartamento';p.status=p.status||'Consultar disponibilidade';p.price=value.price===null||value.price===''?null:Number(value.price);if(p.price!==null&&(!Number.isFinite(p.price)||p.price<=0||p.price>1000000000))throw new HttpError(400,'Preço inválido.');for(const key of ['rooms','roomsMax']){p[key]=Number(value[key]||0);if(!Number.isInteger(p[key])||p[key]<0||p[key]>100)throw new HttpError(400,'Quantidade de quartos inválida.');}if(p.roomsMax<p.rooms)p.roomsMax=p.rooms;
const safeImage=(s:string)=>/^https:\/\//i.test(s)||/^\/api\/media\/[a-f0-9-]+\.(jpg|png|webp)$/.test(s)||/^[a-zA-Z0-9_.-]+\.(webp|jpg|png)$/.test(s);
if(!Array.isArray(value.images)||!value.images.length||value.images.length>150||value.images.some((s:any)=>typeof s!=='string'||s.length>2000||!safeImage(s)))throw new HttpError(400,'Inclua de 1 a 150 fotos válidas.');p.images=[...new Set(value.images)];p.source=txt(value.source,2000);if(p.source&&!/^https:\/\//i.test(p.source))throw new HttpError(400,'Use um link HTTPS para o anúncio.');for(const k of ['hidden','launch','featured','customGallery'])p[k]=!!value[k];p.checkedAt=value.checkedAt?txt(value.checkedAt,30):'';return p;}
export async function saveProperty(id:string,value:any,revision:number){if(!Number.isInteger(revision)||revision<0)throw new HttpError(400,'Reabra o anúncio antes de salvar.');if(!/^[a-z0-9-]{1,80}$/.test(id))throw new HttpError(400,'Código interno inválido.');const p={...validateProperty(value),id};if(!p.code)p.code=id;const db=database();const now=new Date().toISOString();let result;if(revision===0)result=await db.prepare('INSERT OR IGNORE INTO property_overrides(id,data,revision,updated_at) VALUES (?,?,1,?)').bind(id,JSON.stringify(p),now).run();else result=await db.prepare('UPDATE property_overrides SET data=?,revision=revision+1,updated_at=? WHERE id=? AND revision=?').bind(JSON.stringify(p),now,id,revision).run();if(!result.meta.changes)throw new HttpError(409,'O anúncio mudou em outra sessão. Reabra antes de salvar.');return {...p,revision:revision+1};}
