import {cookies} from 'next/headers';
export class HttpError extends Error {constructor(public status:number,message:string){super(message);}}
export function config(){const url=process.env.SUPABASE_URL,publishable=process.env.SUPABASE_PUBLISHABLE_KEY,secret=process.env.SUPABASE_SECRET_KEY;if(!url||!publishable||!secret)throw new Error('Configure as três variáveis do Supabase na hospedagem.');return {url,publishable,secret};}
export async function rest(path:string,options:RequestInit={},token?:string){const c=config();const key=token?c.publishable:c.secret;const response=await fetch(c.url+'/rest/v1/'+path,{...options,cache:'no-store',headers:{apikey:key,...(token?{Authorization:'Bearer '+token}:{}),'Content-Type':'application/json',...options.headers},signal:AbortSignal.timeout(20000)});const raw=await response.text();const data=raw?JSON.parse(raw):null;if(!response.ok){if(response.status===409)throw new HttpError(409,'O anúncio mudou em outra sessão. Reabra antes de salvar.');throw new HttpError(response.status===401||response.status===403?403:503,'Não foi possível concluir a operação. Tente novamente.');}return data;}
const options={httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax' as const,path:'/'};
export async function authRequest(path:string,body?:unknown,token?:string){const c=config();return fetch(c.url+'/auth/v1/'+path,{method:body?'POST':'GET',headers:{apikey:c.publishable,'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store',signal:AbortSignal.timeout(15000)});}
export async function saveSession(session:any){const jar=await cookies();jar.set('ac-access',session.access_token,{...options,maxAge:session.expires_in||3600});jar.set('ac-refresh',session.refresh_token,{...options,maxAge:30*86400});}
export async function clearSession(){const jar=await cookies();jar.set('ac-access','',{...options,maxAge:0});jar.set('ac-refresh','',{...options,maxAge:0});}
export async function authorized(){const jar=await cookies();let token=jar.get('ac-access')?.value;const refresh=jar.get('ac-refresh')?.value;let response=token?await authRequest('user',undefined,token):null;if(!response?.ok&&refresh){const r=await authRequest('token?grant_type=refresh_token',{refresh_token:refresh});if(r.ok){const session=await r.json();await saveSession(session);token=session.access_token;response=await authRequest('user',undefined,token);}}
if(!token||!response?.ok)throw new HttpError(401,'Entre com seu e-mail e senha.');const user=await response.json();if(!user.email_confirmed_at||await rest('rpc/is_site_admin',{method:'POST',body:'{}'},token)!==true)throw new HttpError(403,'Esta conta não tem acesso ao painel.');return {...user,token};}
export function sameOrigin(req:Request){if(req.headers.get('Origin')!==new URL(req.url).origin)throw new HttpError(403,'Origem não autorizada.');}
export const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
