const fs=require('fs'),path=require('path'),ts=require('typescript'),Module=require('module'),assert=require('assert/strict');const {DatabaseSync}=require('node:sqlite');
const sqlite=new DatabaseSync(':memory:');const migration=fs.readdirSync('drizzle').find(f=>f.endsWith('.sql'));sqlite.exec(fs.readFileSync('drizzle/'+migration,'utf8').replaceAll('--> statement-breakpoint',''));
const DB={prepare(sql){let values=[];return {bind(...args){values=args;return this},async first(){return sqlite.prepare(sql).get(...values)},async all(){return {results:sqlite.prepare(sql).all(...values)}},async run(){const r=sqlite.prepare(sql).run(...values);return {meta:{changes:Number(r.changes)}}}}}};
const files=new Map();const BUCKET={async put(key,data,opt){files.set(key,{data,opt});},async get(key){const f=files.get(key);return f?{body:f.data,httpMetadata:f.opt.httpMetadata}:null}};
let user=null;const env={DB,BUCKET,ADMIN_OWNER_EMAIL:'owner@example.test'};
function load(file,overrides={}){const name=path.resolve(file);const mod=new Module(name,module);mod.filename=name;mod.paths=Module._nodeModulePaths(path.dirname(name));const original=mod.require.bind(mod);mod.require=id=>{if(id==='cloudflare:workers')return {env};if(id.endsWith('chatgpt-auth'))return {getChatGPTUser:async()=>user};if(id in overrides)return overrides[id];if(id.endsWith('?raw'))return fs.readFileSync(path.resolve(path.dirname(name),id.slice(0,-4)),'utf8');return original(id)};const code=ts.transpileModule(fs.readFileSync(name,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;mod._compile(code,name);return mod.exports;}
const store=load('app/store.ts');const api=load('app/api/[...path]/route.ts',{'../../store':store});const root=load('app/route.ts',{'./store':store});const panel=load('app/painel/route.ts',{'../store':store});
async function request(route,method='GET',value,origin=true){const headers=method==='GET'?{}:{'Content-Type':'application/json',...(origin?{Origin:'https://test.example'}:{})};return api[method](new Request('https://test.example/api/'+route,{method,headers,...(value?{body:JSON.stringify(value)}:{})}));}
(async()=>{
assert.equal((await request('admin/leads')).status,401);assert.equal((await request('admin/properties')).status,401);assert.ok((await (await panel.GET()).text()).includes('/signin-with-chatgpt'));
user={email:'intruder@example.test',userId:'bad'};assert.equal((await request('admin/leads')).status,403);
user={email:'owner@example.test',userId:'owner-id'};let rows=await (await request('admin/properties')).json();assert.equal(rows.length,460);assert.ok(rows.every(p=>p.images.length));const original=rows.find(p=>p.id==='brazville');
assert.equal((await request('admin/property/brazville','PUT',{revision:0,property:original},false)).status,403);
let edited={...original,title:'Test updated title',price:1750000};let result=await request('admin/property/brazville','PUT',{revision:0,property:edited});assert.equal(result.status,200);assert.equal((await store.catalog()).find(p=>p.id==='brazville').price,1750000);assert.equal((await request('admin/property/brazville','PUT',{revision:0,property:edited})).status,409);
const fresh={...edited,id:'manual-test',code:'',title:'New test property',images:['https://example.test/photo.jpg'],customGallery:true};assert.equal((await request('admin/property/manual-test','PUT',{revision:0,property:fresh})).status,200);assert.equal((await store.catalog()).length,461);assert.deepEqual((await (await request('gallery?id=manual-test')).json()).images,fresh.images);
const hidden={...fresh,hidden:true};assert.equal((await request('admin/property/manual-test','PUT',{revision:1,property:hidden})).status,200);assert.equal((await store.catalog()).length,460);assert.equal((await request('gallery?id=manual-test')).status,404);
assert.equal((await request('admin/property/manual-invalid','PUT',{revision:0,property:{...fresh,images:['javascript:alert(1)']}})).status,400);assert.equal((await request('admin/property/manual-invalid','PUT',{revision:-1,property:fresh})).status,400);
const lead={id:crypto.randomUUID(),name:'Test Client',phone:'(41) 99999-9999',email:'client@example.test',goal:'Agendar uma visita',wish:'Test request'};user=null;assert.equal((await request('lead','POST',{...lead,phone:''})).status,400);assert.equal((await request('lead','POST',{...lead,email:'bad'})).status,400);assert.equal((await request('lead','POST',lead)).status,200);assert.equal((await request('lead','POST',lead)).status,200);assert.equal((await request('admin/leads')).status,401);
user={email:'ariannecostaimoveis@gmail.com',userId:'arianne-id'};const contacts=await(await request('admin/leads')).json();assert.equal(contacts.length,1);assert.equal(contacts[0].phone,lead.phone);assert.equal(contacts[0].email,lead.email);assert.equal((await request('admin/lead/'+lead.id,'PATCH',{status:'Em atendimento'})).status,200);
user={email:'ariannecostaimoveis@gmail.com',userId:'different-id'};assert.equal((await request('admin/leads')).status,403);
user=null;await request('event','POST',{route:'imovel/brazville',kind:'view'});await request('event','POST',{route:'imovel/brazville',kind:'view'});assert.equal((await request('event','POST',{route:'imovel/unknown',kind:'view'})).status,400);
user={email:'owner@example.test',userId:'owner-id'};assert.equal((await(await request('admin/stats')).json())[0].count,2);
const form=new FormData();form.append('file',new File([new Uint8Array([137,80,78,71,13,10,26,10,1,2,3,4,5,6,7,8])],'test.png',{type:'image/png'}));const upload=await api.POST(new Request('https://test.example/api/admin/upload',{method:'POST',headers:{Origin:'https://test.example'},body:form}));assert.equal(upload.status,200);const image=await upload.json();assert.equal((await request(image.url.replace('/api/',''))).status,200);assert.equal((await request('media/../../x')).status,404);
const homepage=await root.GET();assert.equal(homepage.status,200);const html=await homepage.text();assert.ok(html.includes('Test updated title'));assert.ok(html.includes('id="lead-phone" required'));assert.ok(html.includes('id="lead-email" type="email"'));assert.ok(html.includes('Continuar a conversa no WhatsApp'));assert.ok(!html.includes("window.location.href='https://wa.me/"));assert.equal((await panel.GET()).status,200);console.log('PASS: private access, owner and Arianne access, stable identity, catalog edits, conflicts, new/hidden ads, photo validation and uploads, required phone, optional email, saved and deduplicated contacts, client status, aggregate views, public site and panel.');
})().catch(e=>{console.error(e);process.exitCode=1});
